# Sahi format
spring.data.mongodb.uri=mongodb+srv:///matritvablooddonor_db:Matritva2020@cluster0.xlcvkcc.mongodb.net/blood_donation_db
# Email Config
# Email Config - Switching to Port 465 (More stable for Render)
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=matritvafoundation@gmail.com
spring.mail.password=eyie qkzy nfke ysoz
spring.mail.properties.mail.smtp.auth=true
# SSL Settings
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory

# Timeout settings (Connect timeout badha dete hain)
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
fast2sms.api.key=paTbOGLYJWKmgNhXdrlk9FBvVP68zSR2EjA5cqDe3nwM1I0UQ41ulKU5tXfANh4xzqvsrc9ZyCiOLTjR
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB