# MongoDB Config (Sahi chal raha hai)
spring.data.mongodb.uri=mongodb+srv://matritvablooddonor_db:Matritva2020@cluster0.xlcvkcc.mongodb.net/blood_donation_db?retryWrites=true&w=majority

# Email Config - Back to Port 587 with Force TLS
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=matritvafoundation@gmail.com
spring.mail.password=eyie qkzy nfke ysoz

# Force TLS and Authentication
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

# Timeouts (30 Seconds tak badha diya hai)
spring.mail.properties.mail.smtp.connectiontimeout=30000
spring.mail.properties.mail.smtp.timeout=30000
spring.mail.properties.mail.smtp.writetimeout=30000

# Other Configs
fast2sms.api.key=paTbOGLYJWKmgNhXdrlk9FBvVP68zSR2EjA5cqDe3nwM1I0UQ41ulKU5tXfANh4xzqvsrc9ZyCiOLTjR
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB